- name: Create kubeguest directory
  command: mkdir -p kubeguest

- name: Create frontend service file with public IP
  template: src={{ item }}.json.j2 dest=kubeguest/{{ item }}.json
  with_items:
    - frontend-service

- name: Copy service and controllers
  copy: src={{ item }}.json dest=kubeguest/{{ item }}.json
  with_items:
  - frontend-controller
  - redis-master-controller
  - redis-master-service
  - redis-slave-controller
  - redis-slave-service

- name: Create Redis master controller
  command: kubectl create -f kubeguest/redis-master-controller.json

- name: Create Redis master service
  command: kubectl create -f kubeguest/redis-master-service.json

- name: Create Redis slave controller
  command: kubectl create -f kubeguest/redis-slave-controller.json

- name: Create Redis slave service
  command: kubectl create -f kubeguest/redis-slave-service.json

- name: Create PHP frontend controller 
  command: kubectl create -f kubeguest/frontend-controller.json

- name: Create PHP frontend service
  command: kubectl create -f kubeguest/frontend-service.json


