---
- name: reboot atomic
  command: systemctl reboot
  async: 0
  poll: 0
  ignore_errors: true

- name: reload systemd
  command: systemctl daemon-reload

- name: restart flannel
  service: name=flanneld state=restarted

- name: restart docker
  service: name=docker state=restarted

- name: restart kublet
  service: name=kubelet

- name: restart proxy
  service: name=kube-proxy state=restarted

