---
- name: Open firewalld port for etcd
  firewalld: port={{ item }}/tcp permanent=false state=enabled
  with_items:
    - 4001
    - 7001

- name: Save firewalld port for etcd
  firewalld: port={{ item }}/tcp permanent=true state=enabled
    - 4001
    - 7001
