---
- name: Install etcd from configured repo
  yum: pkg=etcd state=latest
  when: ansible_os_family == "RedHat" and is_atomic == False

- name: Create etcd config
  template: src=etcd.conf.j2 dest=/etc/etcd/etcd.conf

- name: Enable and start etcd
  service: name=etcd enabled=yes state=started

- include: firewalld.yml
  when: has_firewalld == '0'

- include: iptables.yml
  when: has_iptables == '0'

- name: Create flanneld config
  template: src=flanneld-conf.json.j2 dest=/tmp/flanneld-conf.json

- name: POST the config to etcd
  uri: url=http{{ group(etcd)[0] }}:4001/v2/keys/{{ cluster_name }}/network/config method=POST body="{{ lookup('template', 'flanneld-conf.json.j2' }}
  #shell: curl -L http://{{ groups['etcd'][0] }}:4001/v2/keys/{{ cluster_name }}/network/config -XPUT --data-urlencode value@/tmp/flanneld-conf.json
