---
- name: Determine if firewalld installed
  command: "rpm -q firewalld"
  register: has_firewalld
  ignore_errors: yes
  changed_when: false

- name: Determine if iptables-services installed
  command: "rpm -q iptables-services"
  register: has_iptables
  ignore_errors: yes
  changed_when: false

- name: Install docker from configured repo
  yum: pkg=docker-io state=latest
  when: ansible_os_family == "RedHat" #and is_atomic.rc == 1

- name: Install docker-py from configured repo
  yum: pkg=python-docker-py state=latest
  when: ansible_os_family == "RedHat" #and is_atomic.rc == 1

- name: Install kubernetes from configured repo
  yum: pkg=kubernetes state=latest
  when: ansible_os_family == "RedHat" #and is_atomic.rc == 1

- name: Install etcd from configured repo
  yum: pkg=etcd state=latest
  when: ansible_os_family == "RedHat" #and is_atomic.rc == 1

- name: Enable and start etcd
  service: name=etcd enabled=yes state=started

- include: firewalld.yml
  when: has_firewalld.rc == 0

- include: iptables.yml
  when: has_firewalld.rc != 0 and has_iptables.rc == 0

- name: Create flanneld config
  template: src=flanneld-conf.json.j2 dest=/tmp/flanneld-conf.json

- name: POST the config to etcd
  shell: curl -L http://{{ groups['etcd'][0] }}:4001/v2/keys/{{ cluster_name }}/network/config -XPUT --data-urlencode value@/tmp/flanneld-conf.json
