---
- name: Install etcd from configured repo
  yum: pkg=etcd state=latest
  when: ansible_os_family == "RedHat" and is_atomic == False

- name: Enable and start etcd
  service: name=etcd enabled=yes state=started

- include: firewalld.yml
  when: has_firewalld == True

- include: iptables.yml
  when: has_iptables == True

- name: Create flanneld config
  template: src=flanneld-conf.json.j2 dest=/tmp/flanneld-conf.json

- name: POST the config to etcd
  shell: curl -L http://{{ groups['etcd'][0] }}:4001/v2/keys/{{ cluster_name }}/network/config -XPUT --data-urlencode value@/tmp/flanneld-conf.json
