- name: Create kubedns directory
  command: mkdir -p kubedns

- name: Create SkyDNS service file
  template: src=skydns-svc.yaml.j2 dest=kubedns/skydns-svc.yaml

- name: Create SkyDNS controller file
  template: src=skydns-controller.yaml.j2 dest=kubedns/skydns-controller.yaml

- name: Create SkyDNS service
  command: kubectl create -f kubedns/skydns-svc.yaml 

- name: Create SkyDNS replication controller
  command: kubectl create -f kubedns/skydns-controller.yaml 
