---
- name: Open firewalld port for local-registry and apiserver
  firewalld: port={{ item }}/tcp permanent=false state=enabled
  with_items:
    - 5000
    - 8080
    - 7080
    - 8443

- name: Save firewalld port configuration for local-registry and apiserver
  firewalld: port={{ item }}/tcp permanent=true state=enabled
  with_items:
    - 5000
    - 8080
    - 7080
    - 8443

