---
- name: Open firewalld port for local-registry
  firewalld: port=5000/tcp permanent=false state=enabled
  # in case this is also a minion with firewalld turned off
  ignore_errors: yes

- name: Save firewalld port for local-registry
  firewalld: port=5000/tcp permanent=true state=enabled
  # in case this is also a minion with firewalld turned off
  ignore_errors: yes

- name: Open firewalld port for apiserver
  firewalld: port=8080/tcp permanent=false state=enabled
  # in case this is also a minion with firewalld turned off
  ignore_errors: yes

- name: Save firewalld port for apiserver
  firewalld: port=8080/tcp permanent=true state=enabled
  # in case this is also a minion with firewalld turned off
  ignore_errors: yes

- name: Open firewalld port for apiserver
  firewalld: port=7080/tcp permanent=false state=enabled
  # in case this is also a minion with firewalld turned off
  ignore_errors: yes

- name: Save firewalld port for apiserver
  firewalld: port=7080/tcp permanent=true state=enabled
  # in case this is also a minion with firewalld turned off
  ignore_errors: yes

- name: Open firewalld port for apiserver
  firewalld: port=8443/tcp permanent=false state=enabled
  # in case this is also a minion with firewalld turned off
  ignore_errors: yes

- name: Save firewalld port for apiserver
  firewalld: port=8443/tcp permanent=true state=enabled
  # in case this is also a minion with firewalld turned off
  ignore_errors: yes
