---
- name: Enable iptables at boot
  service: name=iptables enabled=yes state=started

- name: Open local-registry apiserver ports with iptables
  command: /sbin/iptables -I INPUT 1 -p tcp --dport {{ item }} -j ACCEPT -m
  with_items:
    - 5000
    - 7070
    - 8080
    - 8443
  notify:
          - restart iptables

- name: Save iptables rules
  command: service iptables save
